### ISSUE TITLE
Висячая пунктуация 

### ISSUE THREAD

**Issue by Wansmer** [typograf/gulp-typograf#4]
Добрый день! Установил Ваш плагин, пытаюсь добавить висячую пунктуацию. 
В документации сказано, что нужно добавить link на typograf.css. 
Нигде в репозиториях не смог найти данный файл. 
При создании файла самостоятельно и добавления туда части css из desktop.min.css висячая пунктуация не срабатывает. 
`.typograf-nowrap{white-space:nowrap}.typograf-oa-sp-lbracket{margin-right:.3em}.typograf-oa-lbracket,.typograf-oa-n-lbracket{margin-left:-.3em}.typograf-oa-comma{margin-right:-.2em}.typograf-oa-comma-sp{margin-left:.2em}.typograf-oa-sp-lquote{margin-right:.44em}.typograf-oa-lquote,.typograf-oa-n-lquote{margin-left:-.44em}`

В gulpfile правило установил:
`
			   .pipe(typograf({
					locale: ['ru', 'en-US'],
					htmlEntity: { type: 'digit' },
					enableRule: ['ru/optalign/*']
			   }))
`
Как подключить висячую пунктуацию при сборке через gulp?
Заранее спасибо.

**Comment by hcodes** [comment]
Добрый день.
Папка `/dist` есть только в npm-пакете `typograf`. В ней как раз есть  файл `typograf.css`.
Можно посмотреть на https://unpkg.com/browse/typograf@6.9.0/dist/

**Comment by Wansmer** [comment]
Спасибо. Я правильно понял, что через gulp инструментарий висячей пунктуации не работает? 
Или нужно вручную скопировать папку dist и добавить в src с проектом?

**Comment by hcodes** [comment]
https://github.com/typograf/gulp-typograf-test/commit/3249d2b8459ad000d2e1be4e90f280534b1258c9

Да, файл `./node_modules/typograf/dist/typograf.css` нужно добавить в сборку своего проекта.

**Comment by Wansmer** [comment]
Спасибо!
